### ISSUE TITLE
Data races are hidden for successful tests

### ISSUE THREAD

**Issue by afinkenstadt** [go-check/check#34] opened 2015-02-27 19:41 UTC
`godep go test -race -cover ./... --environment=dev` will report that all tests pass.

However, running the same tests without gocheck in the test framework results in a data race detection found:

```
WARNING: DATA RACE
Write by goroutine 81:
...elided...

Previous write by goroutine 79:
...identical elided...
```

**Comment by niemeyer** [comment] 2015-02-27 19:46
I cannot reproduce the issue. gocheck doesn't do anything funky with stdout or stderr, so there's no way for it to be hiding anything that is not produced by itself. If you have a reproducer, please provide code and the exact commands for reproducing. I'm closing the issue for the time being, but feel free to open if you find gocheck is to blame and have this data.

**Closed as completed by niemeyer** 2015-02-27 19:46 UTC

**Comment by jonhoo** [comment] 2016-03-04 18:32
@afinkenstadt: I think this is actually an upstream issue. Try running

``` console
$ go test -race 2> test.err > test.log
```

If the test passes, the found races aren't printed in the logs.

**Comment by afinkenstadt** [comment] 2016-03-04 19:26
Looks like.
